title: My Blog
author: Rachakulla Mahesh Sarat Chandra
theme: minima
email: r.mahesh2307@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is to write articles, projects etc..

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
